version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db